package ap

const (
	CASE_CONTENT_UPDATE = ACTIVITY_UPDATE
	CASE_CONTENT_CREATE = ACTIVITY_CREATE
	CASE_CONTENT_DELETE = ACTIVITY_DELETE
)

const (
	CASE_COLLECTION_ADD = ACTIVITY_ADD
	CASE_COLLECTION_MOVE = ACTIVITY_MOVE
	CASE_COLLECTION_REMOVE = ACTIVITY_REMOVE
)

const (
	CASE_REACTION_ACCEPT = ACTIVITY_ACCEPT
	CASE_REACTION_BLOCK = ACTIVITY_BLOCK
	CASE_REACTION_DISLIKE = ACTIVITY_DISLIKE
	CASE_REACTION_FLAG = ACTIVITY_FLAG
	CASE_REACTION_IGNORE = ACTIVITY_IGNORE
	CASE_REACTION_LIKE = ACTIVITY_LIKE
	CASE_REACTION_REJECT = ACTIVITY_REJECT
	CASE_REACTION_TENTATIVEACCEPT = ACTIVITY_TENTATIVEACCEPT
	CASE_REACTION_TENTATIVEREJECT = ACTIVITY_TENTATIVEREJECT
)

const (
	CASE_RSVP_ACCEPT = ACTIVITY_ACCEPT
	CASE_RSVP_IGNORE = ACTIVITY_IGNORE
	CASE_RSVP_INVITE = ACTIVITY_INVITE
	CASE_RSVP_REJECT = ACTIVITY_REJECT
	CASE_RSVP_TENTATIVEACCEPT = ACTIVITY_TENTATIVEACCEPT
	CASE_RSVP_TENTATIVEREJECT = ACTIVITY_TENTATIVEREJECT
)

const (
	CASE_GROUP_ADD = ACTIVITY_ADD
	CASE_GROUP_JOIN = ACTIVITY_JOIN
	CASE_GROUP_LEAVE = ACTIVITY_LEAVE
	CASE_GROUP_REMOVE = ACTIVITY_REMOVE
)

const (
	CASE_CONTENT_LISTEN = ACTIVITY_LISTEN
	CASE_CONTENT_READ = ACTIVITY_LISTEN
	CASE_CONTENT_VIEW = ACTIVITY_LISTEN
)

const (
	CASE_GEOSOCIAL_ARRIVE = ACTIVITY_ARRIVE
	CASE_GEOSOCIAL_LEAVE = ACTIVITY_LEAVE
	CASE_GEOSOCIAL_TRAVEL = ACTIVITY_TRAVEL
)

const (
	CASE_NOTIFICATION_ANNOUNCE = ACTIVITY_ANNOUNCE
)

const (
	CASE_QUESTION_ANNOUNCE = ACTIVITY_QUESTION
)

const (
	CASE_RELATIONSHIP_ACCEPT = ACTIVITY_ACCEPT
	CASE_RELATIONSHIP_ADD = ACTIVITY_ADD
	CASE_RELATIONSHIP_BLOCK = ACTIVITY_BLOCK
	CASE_RELATIONSHIP_CREATE = ACTIVITY_CREATE
	CASE_RELATIONSHIP_DELETE = ACTIVITY_DELETE
	CASE_RELATIONSHIP_FOLLOW = ACTIVITY_FOLLOW
	CASE_RELATIONSHIP_IGNORE = ACTIVITY_IGNORE
	CASE_RELATIONSHIP_INVITE = ACTIVITY_INVITE
	CASE_RELATIONSHIP_REJECT = ACTIVITY_REJECT
)

const (
	CASE_NEGATING_UNDO = ACTIVITY_UNDO
)

const (
	CASE_OFFER_OFFER = ACTIVITY_OFFER
)

























